FROM python:3.10

RUN pip install tox


# Copy only req (avoid copy DB)
COPY  src /repository/src
COPY  tests /repository/tests
COPY  tox.ini /repository/tox.ini
COPY requirements.txt repository/requirements.txt
WORKDIR /repository

CMD tox
