name: run-unit-integration-tests-and-check-style

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: build-linter-image
        run: docker build -f Dockerfile.linting -t stock_analyzer-linting .

      - name: check-linting-tests
        run: docker run stock_analyzer-linting tox

      - name: check-db-and-temp-directory-exist
        run: >-
          directories=("temp" "database"); 
          for directory in "${directories[@]}"; do
              if [ ! -d "$directory" ]; then
                  echo "The directory $directory does not exist. Creating..."
                  mkdir -p "$directory"
                  echo "Directory created successfully!"
              else
                  echo "The directory $directory already exists."
              fi
          done

      - name: build-tests-image
        run: docker build --file Dockerfile.tests --tag stock_analyzer-tests .

      - name: run-unit-tests
        run: >-
          docker run --network=host --volume="$PWD/coverage/":/var/coverage/ stock_analyzer-tests
          bash -c "python3 -m pytest 'tests/unit' --cov src --cov-config tox.ini --cov-report html --cov-report term"

      - name: run-integration-tests
        run: >-
          docker run 
          -e POLYGON_KEY=${{ secrets.POLYGON_KEY }}
          -e FRED_KEY=${{ secrets.FRED_KEY }}
          stock_analyzer-tests
          bash -c "python3 -m pytest 'tests/integration' -s"